# Generated by Django 6.0.7 on 2026-07-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usurarios',
            fields=[
                ('id_usuarioo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(verbose_name=255)),
                ('email', models.TextField(verbose_name=255)),
                ('setor', models.TextField(verbose_name=255)),
            ],
        ),
    ]
