# Generated by Django 6.0.7 on 2026-07-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usurarios',
            new_name='Usuarios',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_usuarioo',
            new_name='id_usuario',
        ),
    ]
