# Generated by Django 6.0.7 on 2026-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usurarios_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='setor',
            field=models.IntegerField(max_length=10),
        ),
    ]
