# Generated by Django 6.0.7 on 2026-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuarios_email_alter_usuarios_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='setor',
            field=models.IntegerField(),
        ),
    ]
