# Generated by Django 6.0.7 on 2026-07-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuarios_email_alter_usuarios_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='setor',
            field=models.CharField(),
        ),
    ]
